### ISSUE TITLE
Form fields ?

### ISSUE THREAD

**Issue by jpic** [percipient/django-querysetsequence#2]
Hi !

So, I put together a [couple of form fields for django-querysetsequence](https://github.com/yourlabs/django-autocomplete-light/blob/v3/src/dal_queryset_sequence/fields.py). As I just saw that you implemented .none(), I thought maybe you were going for Model{,Multiple}ChoiceField compatibility, in which case I was wondering if you wanted to maintain this as part of django-querysetsequence, for other users who are non dal v3 users to enjoy too.

As a side note, I also want to say I really like this app ^^ I wonder if apps like django-generic-m2m or django-gm2m could use it too, you might be curious and check it out.

**Comment by clokep** [comment]
Interesting idea! I added `none()` because it was easy and not yet implemented, not for any particular reason.

I'm having a little bit of trouble grasping how this would be usable outside of `django-autocomplete-light`, it seems to heavily depend on use of `ContentType`. Is there an example of this code in use?

Thanks for pointing on those projects, they both seem related and could possible be used to solve the same problem!

**Comment by jpic** [comment]
Well it depends on the ContentTypeModelField, which replaces ModelChoiceField to take values of "ctypepk-modelpk" instead of "modelpk" ie:

  <option value="3-4">your model</option>

For model of ctype 3 and pk 4. This allows the field's to_python method to get the right model from the QuerySetSequence, as there might be several with pk=4. So, I that's not related to autocomplete-light itself I think, the code is loosely coupled so we could just extract whatever class we think belongs to this or that repo.

However, maybe there would be a way to do without the ctype id now that i think of it, ie. using app_label.model_name, then we needn't contenttypes, but then it would be nice to add a bit more API to QuerySetSequence, ie. get_queryset_for('app_label', 'model_name') and this kind of thing.

NP, I think the community has a lot to win if we start merging stuff and working as a team like django itself for example, we'll have more stability, features, etc ... Thank YOU for your feedback.

:guitar:
