### ISSUE TITLE
Using QuerySets from different databases is not supported

### ISSUE THREAD

**Issue by ba1dr** [percipient/django-querysetsequence#37]
Having 2 models `SomeModel` and `OtherModel`, each is in its own database.

```
aqs = SomeModel.objects.all()
print(aqs.count())  # 12
bqs = OtherModel.objects.all()
print(bqs.count())  # 128
qs = QuerySetSequence(aqs, bqs)
print(aqs.count())
# ProgrammingError: relation "tbl_ets_auctions" does not exist
```

does it modify original queryset? Please add a note to the examples about different databases (seems to be not supported?)

**Comment by clokep** [comment]
I don't think this has been tested before, although I'm a little bit surprised that it doesn't work. It should make copies of each `QuerySet`. How do you have it set-up to use different databases? Are you using a database router or some other technique?

**Comment by ba1dr** [comment]
Yes, I use router

**Comment by clokep** [comment]
I can reproduce this using our internal code-base, it'd be helpful to have a reduce test-case for this in our test suite to actually debug it further! I probably won't have time to look into that too soon though.

**Comment by ba1dr** [comment]
I think the issue is caused by router's processing of the cloned querysets.
The logic inside the router might be different depending of the project. In my case it looks inside `Meta` and looks for the custom `database='dbname'` attribute. Another router (as per django docs) may rely on app name of the model.
If you replace the model with Proxy class this might cause the issue.
No proofs yet, just guessing.

**Comment by clokep** [comment]
Our router is configure similar to https://strongarm.io/blog/multiple-databases-in-django/ (so it uses the `_meta.app_label`), but yeah that could be it. The `QuerySetSequence` replaces the model with a "fake" model, so that's probably what is causing the problem. You can see the code here:

https://github.com/percipient/django-querysetsequence/blob/cee97082a13e243a5225e5c4eb3cecd7b2fd3f7d/queryset_sequence/__init__.py#L332-L337

**Comment by ba1dr** [comment]
I think you can insert the original `app_label` to the fake model. And if you could inherit all `Meta` attributes - this would be very useful too.

**Comment by clokep** [comment]
It should inherit the other `Meta` attributes (see https://github.com/percipient/django-querysetsequence/blob/cee97082a13e243a5225e5c4eb3cecd7b2fd3f7d/queryset_sequence/__init__.py#L330-L333). I think there was an issue if you use an `app_label` that matches a real installed app.
