### ISSUE TITLE
New Version

### ISSUE THREAD

**Issue by yveswehrli** [percipient/django-querysetsequence#54]
The get_queryset() command is very helpful. Can you create a new version for that?

**Comment by clokep** [comment]
I plan to release a new version soon, but I'm not sure when. Sorry for the delay.

**Comment by clokep** [comment]
Didn't get to this before I left on vacation for a few weeks...I'll try to get to it this week. Feel free to ping again if I don't!

**Comment by clokep** [comment]
I just pushed version 0.11 to PyPI.

@jpic / @optiz0r
