### ISSUE TITLE
SyntaxWarning: "is not" with a literal. Did you mean "!="?

### ISSUE THREAD

**Issue by clokep** [percipient/django-querysetsequence#60]
the `low_mark` comparison is not obviously an error.
I get this warning running:
`python manage.py runserver`

> /var/venv/lib/python3.8/site-packages/queryset_sequence/__init__.py:255: SyntaxWarning: "is not" with a literal. Did you mean "!="?                                               
>   if low_mark is not 0:                                              

For this reason I did that change, maybe, not strictly necessary.

_Originally posted by @alfredo-ardito in https://github.com/percipient/django-querysetsequence/issues/58#issuecomment-562550902_

**Comment by clokep** [comment]
I don't see this when running tests on Python 3.7, questions I have:
* Is this a new warning?
* Why was this code originally written to use `is not` here? It seems wrong, will need to investigate more.

**Comment by clokep** [comment]
It looks like this code was originally added in dd3502822ec4b9616aae1b9baaf5342211c992d1, so it has always been that way.

**Comment by alfredo-ardito** [comment]
I guess this warning comes from Python 3.8
I'll investigate and let you know

**Comment by clokep** [comment]
Seems to be [documented in the changelog](https://docs.python.org/3/whatsnew/3.8.html#changes-in-python-behavior):

> The compiler now produces a [`SyntaxWarning`](https://docs.python.org/3/library/exceptions.html#SyntaxWarning) when identity checks (`is` and `is not`) are used with certain types of literals (e.g. strings, numbers). These can often work by accident in CPython, but are not guaranteed by the language spec. The warning advises users to use equality tests (`==` and `!=`) instead. (Contributed by Serhiy Storchaka in [bpo-34850](https://bugs.python.org/issue34850).)

I believe your fix was correct to just change it to a `!=`!

**Comment by alfredo-ardito** [comment]
okay, good to know.

**Comment by clokep** [comment]
Thanks for reporting this!
