### ISSUE TITLE
'QuerySetSequence' object has no attribute 'query'

### ISSUE THREAD

**Issue by Fethienv** [percipient/django-querysetsequence#65]
Hi

This error tiger when enter to admin module list page 
`

Request Method: | GET
-- | --
http://127.0.0.1:8000/admin/shop/product/?e=1
3.0.5
AttributeError
'QuerySetSequence' object has no attribute 'query'

`

**Comment by clokep** [comment]
`QuerySetSequence` does not implement the `query` attribute since it doesn't directly make queries. I'm unsure of how you're trynig to use it, but I'd be surprised if it showed up in admin somehow.

Not implementing `query` should probably be mentioned in the docs though...
